### ISSUE TITLE
No unstar directory

### ISSUE THREAD

**Issue by omgimanerd** [prachi1210/starbot#10]
![image](https://cloud.githubusercontent.com/assets/7121024/18753713/32ca0194-80b4-11e6-9f55-70bc306f2577.png)

An unstar directory does not exist. You should probably just make an empty `unstar` directory and dump a  README in it or write in the README that the user should create one. Or just generate the file in the root directory.

**Comment by prachi1210** [comment]
@omgimanerd The issue has been fixed. Thanks for pointing it out! Kindly check.
