### ISSUE TITLE
Fix clone URL / repository name 

### ISSUE THREAD

**Issue by vipul-sharma20** [prachi1210/starbot#14]
The [README.md](https://github.com/prachi1210/starbot/blob/master/README.md) has : https://github.com/prachi1210/gitbot.git as the git clone URL. The repository name is still `starbot` so `git clone https://github.com/prachi1210/gitbot.git` will give "Repository not found". Please fix the URL or the repository name.
Commit: https://github.com/prachi1210/starbot/commit/7e51c9b1f77f6c635a20d0392aff40b6a66ab707#diff-04c6e90faac2675aa89e2176d2eec7d8R18

**Comment by prachi1210** [comment]
@vipul-sharma20  I've fixed the issue. Thanks for pointing it out.
