### ISSUE TITLE
Create DB to save username & password of every fake user created!

### ISSUE THREAD

**Issue by amarlearning** [prachi1210/starbot#7]
Create a db or a text file, so that who so ever run's this script the data [username & password] of every  fake user should be saved at a common place.

**For example :** 
You wrote this script and ran for the first time. now you want 10 stars. 
script will run and create 10 fake users and give you stars. [**max fake user created are = 10**]

Now i run this script and i want 8 stars, we already have 8 fake users in our DB, so script will not create any fake users and will use the existing data [username & password] to give me 8 stars.

**Comment by prachi1210** [comment]
The script create new users every time to avoid using any accounts that have been flagged by GitHub's spambots. If an account has been flagged, you'd need to write to GitHub support which in my opinion is too much pain.

**Comment by amarlearning** [comment]
There may be a chance that some of the fake users account might be flagged, but we can check that thing via script.

We can put a small check in our script to see whether any account has been flagged or not. If any account has been marked as spam we will remove that particular entry from our database.

Let me know what you think about this @prachi1210 ?

**Comment by prachi1210** [comment]
An account being flagged will not prevent you from logging into it but will display a small message in the task bar saying that certain spam bots think that the account may not be maintained by a human linking it with a message that can be sent to GitHub support. How do you propose implement this check?

**Comment by amarlearning** [comment]
ok!
@prachi1210 can you share the account details that has been flagged by github or a screenshot will also work. so that i can see what kind of message is displayed by github ?

**Comment by prachi1210** [comment]
Sure. Mailed you the credentials.

**Comment by prachi1210** [comment]
Since the code in this repository was simply to show it can be done rather than undermine the system of GitHub by creating a huge fake account database, I think we can close this issue.
